server:
  port: 8080

spring:
#H2 DATABASE
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
      open-in-view: false
  main:
      allow-bean-definition-overriding: true

